[project]
name = "automaton-auditor"
version = "0.1.0"
dependencies = [
    "langgraph>=0.0.10",
    "langchain-google-genai",
    "pydantic>=2.0.0",
    "GitPython",
    "python-dotenv",
    "docling", # For the DocAnalyst PDF parsing
]

[tool.uv]
managed = true
